{{- if .Values.virtualService.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "cnx-order.fullname" . }}
  labels:
    {{- include "cnx-order.labels" . | nindent 4 }}
spec:
  hosts:
  {{- range $host := .Values.virtualService.hosts }}
  - {{ $host }}
  {{- end }}
  gateways:
  {{- range $gateway := .Values.virtualService.gateways }}
  - {{ $gateway }}
  {{- end }}
  http:
  - match:
    - uri:
        prefix: "/order/"
    rewrite:
      uri: "/"
    route:
    - destination:
        host: {{ include "cnx-order.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.service.port }}
{{- end }}