apiVersion: v1
kind: Service
metadata:
  name: {{ include "cnx-risk-admin.fullname" . }}
  labels:
    {{- include "cnx-risk-admin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- with .Values.config.http.port | default .Values.service.targetPort }}
      targetPort: {{ . }}
      {{- end }}
      protocol: TCP
      name: cnx-risk-admin
  selector:
    {{- include "cnx-risk-admin.selectorLabels" . | nindent 4 }}
