# cnx-order "Pre".

image:
  # Overrides the image tag whose default is the chart appVersion.
  pullPolicy: Always
  tag: "pre"

persistence:
  enabled: false
  storageClassName: nfs-hdd
  accessModes:
    - ReadWriteMany

ingress:
  enabled: false
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: pre2.cnx.easyswapcoin.com
      paths:
        - path: /cnx-risk-engine(/|$)(.*)
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

virtualService:
  enabled: true
  hosts:
    - pre.cnx.easyswapcoin.com
    - pre.top.one
  gateways:
    - istio-ingress/gateway-cnx-pre

podDisruptionBudget:
  enabled: true

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
            - key: cloud.google.com/gke-spot
              operator: In
              values:
                - "true"
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - cnx-risk-engine-pre
          topologyKey: "kubernetes.io/hostname"

livenessProbe:
  httpGet:
    path: "/health"
    scheme: HTTP
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 5
readinessProbe:
  httpGet:
    path: "/health"
    scheme: HTTP
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3

filebeat:
  enabled: true
  config:
    cnx-policy.json: |
      {
          "policy": {
              "phases": {
                  "hot": {
                      "min_age": "0ms",
                      "actions": {
                          "rollover": {
                              "max_size": "50GB",
                              "max_age": "30d"
                          }
                      }
                  },
                  "delete": {
                      "min_age": "90d",
                      "actions": {
                          "delete": {}
                      }
                  }
              }
          }
      }
    filebeat.yml: |
      # ============================== Filebeat inputs ===============================
      filebeat.inputs:
      - type: filestream
        id: cnx
        enabled: true
        paths:
          - /app/logs/log.*

      # ======================= Elasticsearch template setting =======================
      setup.template.fields: "fields.yml"
      setup.template.enabled: true
      setup.template.overwrite: true
      setup.ilm.rollover_alias: "cnx-risk-engine"
      setup.ilm.pattern: "{now/M{yyyy-MM}}-000001"
      setup.ilm.enabled: true
      setup.ilm.policy_name: "cnx-log"
      setup.ilm.policy_file: "cnx-policy.json"
      setup.ilm.overwrite: true

      # ================================== Outputs ===================================

      # ---------------------------- Elasticsearch Output ----------------------------
      output.elasticsearch:
        hosts: ["cnx-elasticsearch-pre-master-headless.elastic-stack.svc.cluster.local:9200"]
        protocol: "http"
        
      # ================================= Processors =================================
      processors:
        - drop_fields:
            fields: ["agent", "ecs", "host", "input"]

        - decode_json_fields:
            fields: ["message"]
            process_array: false
            max_depth: 1
            target: "data"
            overwrite_keys: false
            add_error_key: true

config:
  env:
    env: pre
    serviceName: "cnx-risk-engine"
    log:
      pretty: true
      level: error
      path: ./logs/log
      maxAge: 72h
      rotationTime: 1h
    debug: false
